---
- hosts: localhost
  become: yes
  vars:
    - user: 'zozitak'
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  tasks:
    - name: "Install Git"
      register: updatesys
      apt:
        update_cache: yes
        name: git-all
        state: present

    - name: "Install Curl"
      register: updatesys
      apt:
        update_cache: yes
        name: curl
        state: present

    - name: "Install Htop"
      register: updatesys
      apt:
        update_cache: yes
        name: htop
        state: present

    - name: "Install Virtualbox"
      register: updatesys
      apt:
        update_cache: yes
        name: virtualbox
        state: present

    - name: "Install Vagrant"
      register: updatesys
      apt:
        update_cache: yes
        name: vagrant
        state: present

    - name: "Install Libre Office"
      register: updatesys
      apt:
        update_cache: yes
        name: libreoffice
        state: present

    - name: "Install Calibre"
      register: updatesys
      apt:
        update_cache: yes
        name: calibre
        state: present
        
    - name: "Install Inkscape"
      community.general.snap:
        name: inkscape
        state: present

    - name: "Install Gimp"
      community.general.snap:
        name: gimp
        classic: true
        state: present

    - name: "Install Blender"
      community.general.snap:
        name: blender
        classic: true
        state: present

    - name: "Install Visual Studio Code"
      community.general.snap:
        name: code
        classic: true
        state: present
        
    - name: "Install Discord"
      community.general.snap:
        name: discord
        state: present
        
    - name: Does the Google apt file exist?
      command: test -f 
      register: google_apt_exists
      ignore_errors: True
      
    - name: Add Google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1
      
    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest= owner=root group=root mode=644
      when: google_apt_exists.rc == 1
      
    - name: Update apt cache
      apt: update_cache=yes
      when: google_apt_exists.rc == 1
      
    - name: Install Google Chrome
      apt: pkg=google-chrome-stable state=present
