---
- hosts: localhost
  become: yes

  tasks:
    - name: "Install Cli"
      register: updatesys
      apt:
        update_cache: yes
        name: 
          - git-all
          - curl
          - htop
          - xclip
          - tree
          - tmux
        state: present
