---
- name: "Install Cli"
  register: updatesys
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
    loop:
      - git-all
      - curl
      - htop
      - xclip
      - tree
      - tmux    
